# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e506defcb0ac304278bd9002301141591922505757ecf47c5da47b70ca9cdad179e89cb310317ce3f72f6f3d811c4113ae0a6293454f930463d1e94081fa51a

test:
  secret_key_base: 1c722ff19a4da6449dff97e5def536080b2d389117cb9d6ad463ef8d1e4831e01dcdf9ef705c44531abda6c8c7d15161d78340a7d36f1381ae4227394bc701bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
